### ISSUE TITLE
 Error in sample model Multiply 2 layers

### ISSUE THREAD

**Issue by pcav** [qgis/QGIS-Processing#12]
Traceback (most recent call last):
  File
"/usr/share/qgis/python/plugins/processing/modeler/EditModelAction.py",
line 41, in execute
    dlg = ModelerDialog(self.alg.getCopy())
  File
"/usr/share/qgis/python/plugins/processing/modeler/ModelerDialog.py",
line 190, in __init__
    self.repaintModel()
  File
"/usr/share/qgis/python/plugins/processing/modeler/ModelerDialog.py",
line 350, in repaintModel
    self.scene.paintModel(self.alg)
  File
"/usr/share/qgis/python/plugins/processing/modeler/ModelerScene.py",
line 101, in paintModel
    value = alg.params[parameter.name]
KeyError: 'GRIDS'

**Comment by borysiasty** [comment]
Does this error occur in English localization, or in Italian only? I had a similar problem with the 'Models' branch in the Options dialog. The key is translatable, so there is a risk its both translations are not equal.

**Comment by pcav** [comment]
Confirmed both in IT and in EN. Thanks.

**Comment by pcav** [comment]
Rasterize and fill trhows a similar error when modifying it:

Errore durante l'esecuzione di codice Python:


Traceback (most recent call last):
  File "/home/paolo/Scrivania/analisi/config/python/plugins/processing/modeler/EditModelAction.py", line 41, in execute
    dlg = ModelerDialog(self.alg.getCopy())
  File "/home/paolo/Scrivania/analisi/config/python/plugins/processing/modeler/ModelerDialog.py", line 190, in __init__
    self.repaintModel()
  File "/home/paolo/Scrivania/analisi/config/python/plugins/processing/modeler/ModelerDialog.py", line 350, in repaintModel
    self.scene.paintModel(self.alg)
  File "/home/paolo/Scrivania/analisi/config/python/plugins/processing/modeler/ModelerScene.py", line 101, in paintModel
    value = alg.params[parameter.name]
KeyError: 'OUTPUT'
